version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"
    networks:
      - docubuntuphp7
    volumes:
      - ./public_html:/var/www/html
      - ./configs/apache/apache2.conf:/etc/apache2/apache2.conf
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./databases:/bin/db_resources
      - ../mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - docubuntuphp7

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      - docubuntuphp7
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

networks:
  docubuntuphp7:
    driver: bridge
